### PR TITLE
Suggestions

### PR DESCRIPTION
**Pull request by jsquyres**
See individual commits / commit messages for details.

### CODE REVIEW

**Comment by jsquyres** [comment]
NOTE: I haven't actually tried to run this (because I need a sample tasks-to-monitor JSON file).  So there may be some typos / bugs in here...

**Comment by fowlerk** [comment]
@jsquyres 
I'm okay with these changes to use the 'standard' logging and Slack routines...I'd looked quickly at using those before but seemed to recall I had a couple of minor nits with using them for both my development / testing and for 'production'.

When I'm doing development / testing on my own system, I prefer to direct errors and debugging info to my own channels, email, etc., not to the 'production' ECC ones.  I recall that the domain for instance in the email error handler was hard-coded to the Epiphany domain.  Sure, I could add code to override that but it just complicates things I think...as an example, I've included the email domain in my GMail credentials file, so I just replace one set of credentials for testing on my system with another for ECC when deploying.  Similar issues with the Slack creds...I notice that the channel is hard-coded in the ECC module as '#bot-errors' as the default.  Again, I know I can override this with a command-line argument when testing, it just adds a bit of complication (and more importantly, remembering!) to my testing.

I'm not sure off-hand of any other repercussions without doing some further testing with referencing these modules, and it's probably the right way to go, I just haven't had the time to test those changes.

**Comment by jsquyres** [comment]
Fair enough, and yes, these cloud-based deployments definitely do add a level of complexity for handling the credentials/channels/etc.  As you noted, I made the slack channel and the "from" address parameters to the setup routines, so they definitely can be overridden for dev/testing.  I'm open to suggestion to how to make that more convenient -- maybe also looking at env variables?  Or having a top-level config file that has all these values in them (creds, slack channel, from email address, etc.).  Then at least it's a single config file for dev/testing at home, and a different config file for production.

If you're ok with these commits, can you merge this PR?  It will add these commits to https://github.com/epiphany40223/epiphany/pull/315.

**Comment by fowlerk** [comment]
Merging your suggestions...will provide a requirements.txt file later.

**Pull request merged**
